server:
  port: 8086
  

spring:
  rabbitmq:
    host: ${global.rabbitmq.host}
    port: ${global.rabbitmq.port}
    username: ${global.rabbitmq.username}
    password: ${global.rabbitmq.password}
  data:
    redis:
      host: ${global.redis.host}
      port: ${global.redis.port}
      password: ${global.redis.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**
              

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**

            - id: job-service
              uri: lb://job-service
              predicates:
                - Path=/api/v1/jobs/**

            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/v1/applications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

