spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-auth
  datasource:
    url: jdbc:postgresql://application_postgres:5432/application_db
    username: ${global.database.application-service.username}
    password: ${global.database.application-service.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    url: jdbc:postgresql://application_postgres:5432/application_db
    user: ${global.database.application-service.username}
    password: ${global.database.application-service.password}
    baseline-description: "init"
    enabled: true
  rabbitmq:
    username: ${global.rabbitmq.username}
    password: ${global.rabbitmq.password}
    port: ${global.rabbitmq.port}
    host: ${global.rabbitmq.host}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8085
