spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth
  datasource:
    url: jdbc:postgresql://localhost:5443/application_db
    username: application_user
    password: '{cipher}965bb0a2393f9213e1fe632a1aa1515cb1a83e873a706f6837beda0155350346b447b7a8a93475b74b8ae014041d1a5e'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5443/application_db
    user: application_user
    password: '{cipher}965bb0a2393f9213e1fe632a1aa1515cb1a83e873a706f6837beda0155350346b447b7a8a93475b74b8ae014041d1a5e'
    baseline-description: "init"
    enabled: true
  rabbitmq:
    username: ${global.rabbitmq.username}
    password: ${global.rabbitmq.password}
    port: ${global.rabbitmq.port}
    host: ${global.rabbitmq.host}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
