spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/auth_db
    username: auth_user
    password: pass_for_auth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
  data:
    redis:
      host: localhost
      port: 6380
      password: sylvester@life
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
keycloak:
  server-url: http://localhost:8079
  realm: spring-auth
  client-id: auth-cli
  client-secret: YIepD1VtVzrFKFpyam02tbUL2iJImoLP
server:
  port: 8081
