spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/auth_db
    username: ${global.database.auth-service.username}
    password: ${global.database.auth-service.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
  data:
    redis:
      host: ${global.redis.host}
      port: ${global.redis.port}
      password: ${global.redis.password}
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
keycloak:
  server-url: http://localhost:8079
  realm: spring-auth
  client-id: auth-cli
  client-secret: '{ciper}6d0c55e11d29799d5898978d125796d5a1fbec7d7acefc047d7bfaef4cc0c8d1aaaf687849e02d119b2ad8e8d55a62335125d03a61512ced8c5190f17de84647'
server:
  port: 8081
