spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth
  datasource:
    url: jdbc:postgresql://localhost:5441/company_db
    username: company_user
    password: '{ciper}6c9167d43bfbc48afbea9c5d3229ca081240e39f89d8d8e7e9d40b9b820bb26244163efe8885d4c3cafd3d77098f0c16'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5441/company_db
    user: company_user
    password:  '{ciper}6c9167d43bfbc48afbea9c5d3229ca081240e39f89d8d8e7e9d40b9b820bb26244163efe8885d4c3cafd3d77098f0c16'
    baseline-description: "init"
    enabled: true
  rabbitmq:
    username: ${global.rabbitmq.username}
    password: ${global.rabbitmq.password}
    port: ${global.rabbitmq.port}
    host: ${global.rabbitmq.host}
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

