spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth
  datasource:
    url: jdbc:postgresql://localhost:5442/job_db
    username: job_user
    password: '{cipher}deb95df9795b548651b190c8678f7f17429839cafcf63d2678f27e07a491e698'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5442/job_db
    user: job_user
    password: '{cipher}deb95df9795b548651b190c8678f7f17429839cafcf63d2678f27e07a491e698'
    baseline-description: "init"
    enabled: true
  rabbitmq:
    username: ${global.rabbitmq.username}
    password: ${global.rabbitmq.password}
    port: ${global.rabbitmq.port}
    host: ${global.rabbitmq.host}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084


