spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/spring-auth
  datasource:
    url: jdbc:postgresql://localhost:5442/job_db
    username: job_user
    password: pass_for_job
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5442/job_db
    user: job_user
    password: pass_for_job
    baseline-description: "init"
    enabled: true
  rabbitmq:
    username: onahsylvester3@gmail.com
    password: sylvester4life
    port: 5671
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084


