spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sylvesteroyonah@gmail.com
    password: '{ciper}9a0ba6022ce53d69e0bba3d5d48f33b7af10f650dc8b30ba02c999d45be42cc6a2334906742119d9e0a0840f2eda3452'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${global.rabbitmq.host}
    port: ${global.rabbitmq.port}
    username: ${global.rabbitmq.username}
    password: ${global.rabbitmq.password}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082

