spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sylvesteroyonah@gmail.com
    password: kjff lsli wajk dctk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5671
    username: onahsylvester3@gmail.com
    password: sylvester4life
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084

