spring:
  message: "Hello user from cloud bus updated 3"
  datasource:
    url: jdbc:postgresql://localhost:5440/auth_db
    username: auth_user
    password: pass_for_auth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5440/auth_db
    user: auth_user
    password: pass_for_auth
    baseline-description: "init"
    enabled: true
  rabbitmq:
    username: onahsylvester3@gmail.com
    password: sylvester4life
    port: 5671
    host: localhost
  data:
    redis:
      host: redis
      port: 6379
      password: sylvester@life
jwt:
  access-expiration: 900000
  refresh-expiration: 604800000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
